name: On Main Push

on:
    push:
        branches:
            - "main"

jobs:
    main:
        runs-on: ubuntu-latest

        outputs:
            label-names: ${{ steps.get-labels.outputs.label-names }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            # May not need this...
            # - name: Get Package Version
            #   id: package-version
            #   uses: martinbeentjes/npm-get-version-action@main

            # - name: Use Node
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: 20.x
            #       cache: "npm"
            # - run: npm ci

            - name: Post Merge PR Label Getter
              id: get-labels
              uses: revrenlove/post-merge-pr-label-getter@v1.0.5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Bump Patch
              uses: phips28/gh-action-bump-version@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  version-type: "patch"
                  skip-commit: "true"
                  skip-tag: "true"

            - name: Bump Minor
              if: ${{ contains(fromJson(steps.get-labels.outputs.label-names), 'minor') }}
              uses: phips28/gh-action-bump-version@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  skip-commit: "true"
                  skip-tag: "true"
                  version-type: "minor"

            - name: Bump major
              if: ${{ contains(fromJson(steps.get-labels.outputs.label-names), 'major') }}
              uses: phips28/gh-action-bump-version@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  skip-commit: "true"
                  skip-tag: "true"
                  version-type: "major"

            - name: Bump Pre-release
              if: ${{ contains(fromJson(steps.get-labels.outputs.label-names), 'pre-release') }}
              uses: phips28/gh-action-bump-version@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  skip-commit: "true"
                  skip-tag: "true"
                  version-type: "prerelease"

            - name: Create Version Bump Pull Request
              id: create-pr
              uses: peter-evans/create-pull-request@v6

            - name: Merge Version Bump Pull Request
              uses: juliangruber/merge-pull-request-action@v1.3.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ steps.create-pr.outputs.pull-request-number }}
                  method: squash

    # create-release:
    #     needs: main
    #     if: ${{ contains(fromJson(needs.main.outputs.label-names), 'release') }}
    #     uses: ./.github/workflows/create-release.yml
